# Generated by Django 2.2.8 on 2020-06-22 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('describtion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('store', models.CharField(blank=True, max_length=30)),
                ('deivery_method', models.CharField(choices=[('has_driver', 'has_driver'), ('use_our_drivers', 'use_our_drivers')], default='user_our_drivers', max_length=17, verbose_name='Delivery Method')),
                ('describtion', models.TextField()),
                ('cash', models.BooleanField()),
                ('credit_card', models.BooleanField()),
                ('k_net', models.BooleanField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/seller', verbose_name='cover')),
                ('commision', models.FloatField(default=0.0)),
                ('allowed_categories', models.ManyToManyField(related_name='sellers', to='product.Category')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Phone')),
                ('password', models.CharField(max_length=128)),
                ('authorization', models.CharField(choices=[('admin', 'Admin'), ('accountant', 'Accountant'), ('seller', 'Seller')], max_length=10)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('active', 'Active'), ('unactive', 'Unactive')], default='pending_approval', max_length=16)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='seller.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='SellerImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/seller')),
                ('image_type', models.CharField(choices=[('website', 'Website'), ('mobile', 'Mobile')], max_length=7)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='seller.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='DealImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/deals')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='seller.Deal')),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='seller.Seller'),
        ),
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('one_view', 'One View'), ('list_view', 'List View')], max_length=9)),
                ('categories', models.ManyToManyField(related_name='customization', to='product.Category')),
                ('deals', models.ManyToManyField(related_name='customization', to='seller.Deal')),
                ('products', models.ManyToManyField(related_name='customization', to='product.Product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customization', to='seller.Seller')),
            ],
        ),
    ]
