# Generated by Django 2.2.8 on 2020-06-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='reset_password_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
