# Generated by Django 2.2.8 on 2020-06-22 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('notify_type', models.CharField(choices=[('welcome', 'Welcome'), ('forget_password', 'Forget_Password'), ('driver_assigned_order', 'Driver_Order'), ('cancel_order', 'Cancel_Order'), ('change_order_status', 'Change_Order_Status')], default='welcome', max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
