# Generated by Django 2.2.8 on 2020-06-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ManyToManyField(related_name='seller_orders', to='seller.Seller'),
        ),
    ]
